version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev # <---- use the dev stage!
    volumes:
      - .:/app # mount your code so air sees changes
      - /app/tmp # keep the tmp dir inside container if you like
    ports:
      - "${PORT}:${PORT}"
    environment:
      # you can still pass along same envs
      APP_ENV: dev
      PORT: ${PORT}
      # ... your DB envs
    depends_on:
      psql:
        condition: service_healthy
    networks:
      - orchestrator

  psql:
    # leave this unchanged (or copy from your existing compose)
    image: postgres:latest
    # …
    # healthcheck, volumes, networks, etc.

networks:
  orchestrator:
volumes:
  psql_volume:
